# baker.py
import base64
import sys

# input_file = "qwen.tiktoken"
# output_hpp = "include/frokenizer_generated/baked.hpp"

table_bits = 18
table_size = 1 << table_bits
mask = table_size - 1
# knuth's golden ratio for bpe pairs
magic_64 = 11400714819323198485 
empty_key = (1 << 64) - 1

def fnv1a(data: bytes) -> int:
    h = 14695981039346656037
    for b in data:
        h ^= b
        h = (h * 1099511628211) & 0xffffffffffffffff
    return h

def bake(input_file, output_hpp):
    print(f"[*] reading {input_file} ...")
    
    raw_tokens = []
    max_rank = 0
    with open(input_file, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line: continue
            b64, rank_str = line.split()
            rank = int(rank_str)
            raw_tokens.append((base64.b64decode(b64), rank))
            if rank > max_rank:
                max_rank = rank

    raw_tokens.sort(key=lambda x: x[1])
    vocab_size = len(raw_tokens)
    print(f"[*] found {vocab_size} tokens. max rank is {max_rank}")

    # base bytes
    base_to_rank = [0] * 256
    active_vocab = {}
    for b_seq, rank in raw_tokens:
        active_vocab[b_seq] = rank
        if len(b_seq) == 1:
            base_to_rank[b_seq[0]] = rank

    print("[*] reconstructing bpe merge tree ...")
    merges = {}
    for i, (b_seq, rank) in enumerate(raw_tokens):
        if len(b_seq) == 1: continue
        parts = [bytes([b]) for b in b_seq]
        while len(parts) > 2:
            min_rank = float('inf')
            min_idx = -1
            for j in range(len(parts) - 1):
                pair = parts[j] + parts[j+1]
                pair_rank = active_vocab.get(pair)
                if pair_rank is not None and pair_rank < rank and pair_rank < min_rank:
                    min_rank = pair_rank
                    min_idx = j
            if min_idx == -1:
                print(f"fatal: could not reconstruct bpe for token {rank}")
                sys.exit(1)
            parts[min_idx] = parts[min_idx] + parts[min_idx+1]
            del parts[min_idx+1]
        
        left_rank = active_vocab[parts[0]]
        right_rank = active_vocab[parts[1]]
        merges[(left_rank, right_rank)] = rank

    print("[*] baking bpe fibonacci hash table ...")
    bpe_table = [(empty_key, 0)] * table_size
    for (l, r), result in merges.items():
        key = (l << 32) | r
        idx = ((key * magic_64) & empty_key) >> (64 - table_bits)
        while bpe_table[idx][0] != empty_key:
            idx = (idx + 1) & mask
        bpe_table[idx] = (key, result)

    print("[*] baking decoder data & fast-path chunk table ...")
    
    array_size = max_rank + 1
    vocab_bytes = [b""] * array_size
    for b_seq, rank in raw_tokens:
        vocab_bytes[rank] = b_seq

    vocab_offsets = [0] * array_size
    vocab_lengths = [0] * array_size
    vocab_string_data = bytearray()
    
    chunk_table = [(empty_key, 0)] * table_size

    current_offset = 0
    for i in range(array_size):
        seq = vocab_bytes[i]
        vocab_offsets[i] = current_offset
        vocab_lengths[i] = len(seq)
        vocab_string_data.extend(seq)
        current_offset += len(seq)

        if len(seq) > 0:
            h = fnv1a(seq)
            idx = h & mask
            while chunk_table[idx][0] != empty_key:
                idx = (idx + 1) & mask
            chunk_table[idx] = (h, i)

    print("[*] baking 256x256 static base pair table ...")
    base_pair_ranks = [[4294967295 for _ in range(256)] for _ in range(256)]
    for i in range(256):
        for j in range(256):
            b_pair = bytes([i, j])
            if b_pair in active_vocab:
                base_pair_ranks[i][j] = active_vocab[b_pair]

    print(f"[*] generating {output_hpp} ...")
    with open(output_hpp, "w", encoding="utf-8") as f:
        f.write("// baked.hpp\n")
        f.write("// AUTO-GENERATED BY scripts/baker.py\n")
        f.write("// DO NOT EDIT !\n\n")
        f.write("#ifndef BAKED_HPP\n#define BAKED_HPP\n\n")
        f.write("#include <cstdint>\n\n")
        f.write("namespace frokenizer \n")
        f.write("{\n\n")
        
        f.write("enum special_token : uint32_t \n")
        f.write("{\n")
        f.write("    token_endoftext = 151643,\n")
        f.write("    token_im_start  = 151644,\n")
        f.write("    token_im_end    = 151645\n")
        f.write("};\n\n")
        
        f.write(f"static constexpr uint32_t vocab_array_size = {array_size};\n")
        f.write(f"static constexpr uint32_t hash_table_size = {table_size};\n")
        f.write(f"static constexpr uint64_t empty_key = ~0ull;\n\n")
        
        f.write("static constexpr uint32_t base_to_rank[256] = {\n    ")
        for i in range(256):
            f.write(f"{base_to_rank[i]}{', ' if i < 255 else ''}")
            if (i + 1) % 16 == 0 and i < 255: f.write("\n    ")
        f.write("\n};\n\n")

        f.write("static constexpr uint32_t base_pair_ranks[256][256] = {\n")
        for i in range(256):
            f.write("    {")
            row = [f"{base_pair_ranks[i][j]}u" for j in range(256)]
            f.write(", ".join(row))
            if i < 255:
                f.write("},\n")
            else:
                f.write("}\n")
        f.write("};\n\n")
        
        f.write("struct merge_entry { uint64_t key; uint32_t result; };\n")
        f.write("static constexpr merge_entry merge_table[hash_table_size] = {\n")
        for i in range(table_size):
            k, v = bpe_table[i]
            f.write(f"{{{k}ull, {v}}}")
            if i < table_size - 1: f.write(",")
            if (i + 1) % 4 == 0: f.write("\n")
            else: f.write(" ")
        f.write("};\n\n")

        f.write("struct chunk_entry { uint64_t hash; uint32_t token_id; };\n")
        f.write("static constexpr chunk_entry chunk_table[hash_table_size] = {\n")
        for i in range(table_size):
            k, v = chunk_table[i]
            f.write(f"{{{k}ull, {v}}}")
            if i < table_size - 1: f.write(",")
            if (i + 1) % 4 == 0: f.write("\n")
            else: f.write(" ")
        f.write("};\n\n")

        f.write("static constexpr uint32_t vocab_offsets[vocab_array_size] = {\n    ")
        for i in range(array_size):
            f.write(f"{vocab_offsets[i]}{', ' if i < array_size - 1 else ''}")
            if (i + 1) % 16 == 0 and i < array_size - 1: f.write("\n    ")
        f.write("\n};\n\n")

        f.write("static constexpr uint8_t vocab_lengths[vocab_array_size] = {\n    ")
        for i in range(array_size):
            f.write(f"{vocab_lengths[i]}{', ' if i < array_size - 1 else ''}")
            if (i + 1) % 32 == 0 and i < array_size - 1: f.write("\n    ")
        f.write("\n};\n\n")

        f.write("static constexpr unsigned char vocab_string_data[] = {\n    ")
        for i, b in enumerate(vocab_string_data):
            f.write(f"0x{b:02x}{', ' if i < len(vocab_string_data) - 1 else ''}")
            if (i + 1) % 16 == 0 and i < len(vocab_string_data) - 1: f.write("\n    ")
        f.write("\n};\n\n")

        f.write("} // namespace frokenizer \n")
        f.write("#endif // BAKED_HPP\n")

    print("[*] done!")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"usage:   python3 baker.py <input_file.tiktoken> <output_path.hpp>")
        print(f"example: python3 baker.py qwen.tiktoken include/frokenizer_generated/baked.hpp")
        sys.exit(1)

    in_path = sys.argv[1]
    out_path = sys.argv[2] if len(sys.argv) > 2 else "include/frokenizer_generated/baked.hpp"

    try:
        bake(in_path, out_path)
    except FileNotFoundError:
        print(f"Error: The file '{in_path}' was not found.")
        sys.exit(1)
    except Exception as e:
        print(f"An error occurred: {e}")
        sys.exit(1)
